; PlatformIO — M5Stack CoreS3 (ESP32-S3) AirPlay receiver only.
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = m5cores3
src_dir = main

[env]
monitor_speed = 115200
monitor_filters = direct
build_flags =
	-Wno-maybe-uninitialized
	-Os
	-DCONFIG_SPIRAM_SIZE=8388608

[env:m5cores3]
platform = platformio/espressif32 @ ^6.12.0
framework = espidf
board = m5stack-cores3
board_build.esp-idf.sdkconfig_path = .pio/build/m5cores3/sdkconfig
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_build.partitions = components/board_cores3/partitions.csv
board_upload.flash_size = 16MB
build_flags =
	${env.build_flags}
	-DBSP_CONFIG_NO_GRAPHIC_LIB=0
board_build.cmake_extra_args =
	"-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults.m5cores3"
