#pragma once

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    EVENT_VOICE_WAKEWORD_DETECTED,
    EVENT_VOICE_SPEECH_START,
    EVENT_VOICE_SPEECH_END,
    EVENT_VOICE_REQUEST_SEND,
    EVENT_VOICE_RESPONSE_AUDIO,
    EVENT_VOICE_RESPONSE_TEXT,
    EVENT_VOICE_PLAYBACK_START,
    EVENT_VOICE_PLAYBACK_END,
    EVENT_VOICE_ERROR,

    EVENT_AIRPLAY_CLIENT_CONNECTED,
    EVENT_AIRPLAY_CLIENT_DISCONNECTED,
    EVENT_AIRPLAY_PLAYBACK_START,
    EVENT_AIRPLAY_PLAYBACK_PAUSE,
    EVENT_AIRPLAY_PLAYBACK_STOP,
    EVENT_AIRPLAY_STREAM_START,
    EVENT_AIRPLAY_STREAM_STOP,

    EVENT_AUDIO_DECODE_REQUEST,
    EVENT_AUDIO_DECODE_DONE,
    EVENT_AUDIO_ENCODE_REQUEST,
    EVENT_AUDIO_ENCODE_DONE,
    EVENT_AUDIO_OUTPUT_UNDERFLOW,
    EVENT_AUDIO_OUTPUT_OVERFLOW,
    EVENT_AUDIO_OUTPUT_STARTED,
    EVENT_AUDIO_OUTPUT_STOPPED,

    EVENT_ENV_DATA_READY,
    EVENT_ENV_THRESHOLD_EXCEEDED,

    EVENT_SYSTEM_WIFI_CONNECTED,
    EVENT_SYSTEM_WIFI_DISCONNECTED,
    EVENT_SYSTEM_RESOURCE_LOW,
    EVENT_SYSTEM_BOOT,

    EVENT_ID_COUNT
} event_id_t;

const char *event_id_to_string(event_id_t id);

#ifdef __cplusplus
}
#endif
